### ISSUE TITLE
add : hacktoberfest tag in the topic of the repository

### ISSUE THREAD

**Issue by rohitroy-github** [OpenCodeEra/Open-Code-Era-2.0#10]
### Description

I think your repository in participating in Hacktoberfest but I don't see a Hacktoberfest tag in the topics of the repository. Please add that ASAP according to the guidelines of Hacktoberfest 2023. Reference : https://hacktoberfest.com/participation/

![image](https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/68563695/5542b029-ac3c-4ba4-a0e4-92acbf424941)

**Comment by CodeTorso** [comment]
I will talk about this with maintainer
