### ISSUE TITLE
UI Changes - Hacktoberfest

### ISSUE THREAD

**Issue by Nitish36** [OpenCodeEra/Open-Code-Era-2.0#12]
### Description

Hey there I had a feature request to do. I am planning to add a sign-up and login page for the website and also a small clarification are we allowed to use backend since I am thinking of using php for the database. Please add this to hacktoberfest-accepted label

Thank You !!

**Comment by CodeTorso** [comment]
Actually,

I do not think we need any sign-up or login feature on a website that only displays information.

But we do have sections like contact us which require backend.

Additionally, in the future, we might need a newsletter section where people can provide their email addresses.

I do believe your idea of adding a backend is awesome. But I want to keep the project simple for the next 15 days.

That is the reason I have not added Tailwind CSS or React or any other frameworks, just plain HTML, CSS, and JS.

**Comment by Nitish36** [comment]
So can I work on this newsletter thing?

**Comment by CodeTorso** [comment]
I do believe your idea of adding a backend is awesome. But I want to keep the project simple for the next 15 days.

You may improve front-end section

**Comment by Nitish36** [comment]
Okay I will try to improve the front-end section then. Please assign this under hacktoberfest-accepted label

**Comment by CodeTorso** [comment]
Don't worry. 

The maintainer will get your PR under `hacktoberFest-accepted` label. HacktoberFest does not look for issues with their label.

**Comment by CodeTorso** [comment]
The link in readme section leads you to openCodeEra 1 to check how this site currently look run it on your local computer

Homepages currently does not have any content yet. 

Look into about us and projects section

<img width="1080" alt="Screenshot 2023-10-04 133455" src="https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/129188028/00359473-7068-48f5-a927-e7da6887d66f">
<img width="1079" alt="Screenshot 2023-10-04 133510" src="https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/129188028/165faaea-0f37-4e36-94f9-6767d353c552">

**Comment by Nitish36** [comment]
Okay will surely do this

**Comment by Nitish36** [comment]
https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/91598274/70de9be5-9db3-452b-bfc4-9ffa1d43d5bb


Hey there
Hopefully you will like my work. If yes then I will raise the PR for this. If you want me to do any more changes or add something else do tell

Thank You!!

**Comment by CodeTorso** [comment]
Seems like you have put a lot of time.

Everything look great.

Here's some suggestion:

SO you have added `:hover` pseudo classes to links and projects.

Can you just think of implementing better box shadow colors and background colors.

Don't worry if you are finding it hard to make the changes just make the PR. 

We will create issues later that'll solve them.



Windows 11 has built-in screen recorder in snipping tools.

**Comment by CodeTorso** [comment]
Can you make little changes in home section. I know it's hard to come with something but just try instead of copy from OpenCodeEra 1 just do something else.

At the end if it's not working we can just use that from openCodeEra.

**Comment by Nitish36** [comment]
I will look into these by tomorrow morning. If by chance I am unable to make changes I will create pull request tomorrow

**Comment by Nitish36** [comment]
I have created the PR :)
