### ISSUE TITLE
[BUG 🐞] Incorrect Home Link In Other Html Files In Pages

### ISSUE THREAD

**Issue by MugoBrian** [OpenCodeEra/Open-Code-Era-2.0#15]
### Description

The <a href="/">Home</a> Link in other pages such as about.html redirects the user to file: / which displays the user's file.
Find the screenshot below for reference.

![Screenshot from 2023-10-04 16-10-03](https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/49617104/1c87df91-d59d-461e-9205-7b54dea2f96a)

**Comment by CodeTorso** [comment]
Wait what ?? 

Let me check that. 

You may fix it if it exists.

**Comment by CodeTorso** [comment]
Just checked the code.

You may fix it. Don't worry about HacktoberFest label.

**Comment by MugoBrian** [comment]
Noted. Let me work on the two issues.
