### ISSUE TITLE
[FEATURE 💡] Styling of the user-input form

### ISSUE THREAD

**Issue by vanshajgupta37** [OpenCodeEra/Open-Code-Era-2.0#5]
### Description

![Screenshot (61)](https://github.com/OpenCodeEra/Open-Code-Era-2.0/assets/116676851/fc2fbffe-6f46-491d-9a2e-cf3b172084de)

The user input form on the right hand side in the attached screenshot is very basic in style.
Please assign this issue to me under label of Hacktoberfest, will re-style it and raise the PR.

**Comment by CodeTorso** [comment]
Yeah great idea. Start working we will get the hacktoberFest label when you PR cause that counts not here

**Comment by CodeTorso** [comment]
That is OpenCodeEra 1 https://github.com/OpenCodeEra/OpenCodeEra this is second version of it. Make the PR on that repo

**Comment by vanshajgupta37** [comment]
i started working on it and also raised the issue on the second version as directed, so you can assign it there
